version: '3'
services:
  proxy:
    build: proxy
    container_name: proxy
    volumes: 
    - "./proxy/etc/httpd/conf.d:/usr/local/apache2/conf/conf.d"
    expose:
    - 80
    - 443
    ports:
# Use below to bind to 0.0.0.0
#    - "80:80"
    - "127.0.0.1:80:80"

  es-home:
    image: ${NODE_TAG}
    container_name: es-home
    user: "node"
    working_dir: "/home/extension-scaffold/es-home"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - DO_INSTALL
      - URLPATH=/es/ui
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  es-runtime:
    image: ${NODE_TAG}
    container_name: es-runtime
    user: "node"
    working_dir: "/home/extension-scaffold/es-runtime"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:8081:8081"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  es-common-extensions:
    image: ${NODE_TAG}
    container_name: es-common-extensions
    user: "node"
    working_dir: "/home/extension-scaffold/es-common-extensions"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports:
      - "127.0.0.1:8082:8082"
    environment:
      - DO_INSTALL
      - URLPATH=/es/common
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-rollup:
    image: ${NODE_TAG}
    container_name: ext-example-rollup
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-rollup"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:9092:9092"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-vite:
    image: ${NODE_TAG}
    container_name: ext-example-vite
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-vite"
    volumes:
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports:
      - "127.0.0.1:9098:9098"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-basic:
    image: ${NODE_TAG}
    container_name: ext-example-basic
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-basic"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:9091:9091"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  iframe-example:
    image: ${NODE_TAG}
    container_name: iframe-example
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/iframe-example"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:9095:9095"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-svelte:
    image: ${NODE_TAG}
    container_name: ext-example-svelte
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-svelte"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:5000:5000"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-webpack:
    image: ${NODE_TAG}
    container_name: ext-example-webpack
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-webpack"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:9093:9093"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  ext-example-lit-element:
    image: ${NODE_TAG}
    container_name: ext-example-lit-element
    user: "node"
    working_dir: "/home/extension-scaffold/es-extension-examples/ext-example-lit-element"
    volumes: 
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports: 
      - "127.0.0.1:9094:9094"
    environment:
      - DO_INSTALL
    command: sh -c "npm run container$${PREVIEW_MODE:+-preview}"

  # The nodejs service is just for development
  nodejs:
    image: ${NODE_TAG}
    user: "node"
    working_dir: /home/extension-scaffold
    volumes:
      - "/etc/ssl/certs:/etc/ssl/certs"
      - "../:/home/extension-scaffold"
      - "./home-node:/home/node"
    ports:
      - "127.0.0.1:3000:3000"
    environment: 
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
    stdin_open: true
    tty: true
    command: bash # Use docker-compose exec nodejs bash, then build/run
